country_codes=[{'code':"AF",'country':"Afg'oniston"},
{'code':"AL",'country':"Albaniya"},
{'code':"DZ",'country':"Jazoir"},
{'code':"AS",'country':"Amerika Samoasi"},
{'code':"AD",'country':"Andorra"},
{'code':"AO",'country':"Angola"},
{'code':"AI",'country':"Anguilla"},
{'code':"AQ",'country':"Antarktida"},
{'code':"AG",'country':"Antigua va Barbuda"},
{'code':"AR",'country':"Argentina"},
{'code':"AM",'country':"Armaniston"},
{'code':"AW",'country':"Aruba"},
{'code':"AU",'country':"Avstraliya"},
{'code':"AT",'country':"Avstriya"},
{'code':"AZ",'country':"Ozarbayjon"},
{'code':"BS",'country':"Bagama orollari"},
{'code':"BH",'country':"Bahrayn"},
{'code':"BD",'country':"Bangladesh"},
{'code':"BB",'country':"Barbados"},
{'code':"BY",'country':"Belarus"},
{'code':"BE",'country':"Belgiya"},
{'code':"BZ",'country':"Beliz"},
{'code':"BJ",'country':"Benin"},
{'code':"BM",'country':"Bermud orollari"},
{'code':"BT",'country':"Butan"},
{'code':"BO",'country':"Boliviya"},
{'code':"BA",'country':"Bosniya va Gertsegovina"},
{'code':"BW",'country':"Botsvana"},
{'code':"BR",'country':"Braziliya"},
{'code':"IO",'country':"Britaniya Hind okeani hududi"},
{'code':"VG",'country':"Britaniya Virjiniya orollari"},
{'code':"BN",'country':"Bruney"},
{'code':"BG",'country':"Bolgariya"},
{'code':"BF",'country':"Burkina-Faso"},
{'code':"BI",'country':"Burundi"},
{'code':"KH",'country':"Kambodja"},
{'code':"CM",'country':"Kamerun"},
{'code':"CA",'country':"Kanada"},
{'code':"CV",'country':"Kabo-Verde"},
{'code':"KY",'country':"Kayman orollari"},
{'code':"CF",'country':"Markaziy Afrika Respublikasi"},
{'code':"TD",'country':"Chad"},
{'code':"CL",'country':"Chili"},
{'code':"CN",'country':"Xitoy"},
{'code':"CX",'country':"Rojdestvo oroli"},
{'code':"CC",'country':"Kokos orollari"},
{'code':"CO",'country':"Kolumbiya"},
{'code':"KM",'country':"Komor orollari"},
{'code':"CK",'country':"Kuk orollari"},
{'code':"CR",'country':"Kosta-Rika"},
{'code':"HR",'country':"Xorvatiya"},
{'code':"CU",'country':"Kuba"},
{'code':"CW",'country':"Kyurakao"},
{'code':"CY",'country':"Kipr"},
{'code':"CZ",'country':"Chex Respublikasi"},
{'code':"CD",'country':"Kongo Demokratik Respublikasi"},
{'code':"DK",'country':"Daniya"},
{'code':"DJ",'country':"Jibuti"},
{'code':"DM",'country':"Dominika"},
{'code':"DO",'country':"Dominika Respublikasi"},
{'code':"TL",'country':"Sharqiy Timor"},
{'code':"EC",'country':"Ekvador"},
{'code':"EG",'country':"Misr"},
{'code':"SV",'country':"Qutqaruvchi"},
{'code':"GQ",'country':"Ekvatorial Gvineya"},
{'code':"ER",'country':"Eritreya"},
{'code':"EE",'country':"Estoniya"},
{'code':"ET",'country':"Efiopiya"},
{'code':"FK",'country':"Folklend orollari"},
{'code':"FO",'country':"Farer orollari"},
{'code':"FJ",'country':"Fiji"},
{'code':"FI",'country':"Finlyandiya"},
{'code':"FR",'country':"Fransiya"},
{'code':"PF",'country':"Fransuz Polineziyasi"},
{'code':"GA",'country':"Gabon"},
{'code':"GM",'country':"Gambiya"},
{'code':"GE",'country':"Gruziya"},
{'code':"DE",'country':"Germaniya"},
{'code':"GH",'country':"Gana"},
{'code':"GI",'country':"Gibraltar"},
{'code':"GR",'country':"Gretsiya"},
{'code':"GL",'country':"Grenlandiya"},
{'code':"GD",'country':"Grenada"},
{'code':"GU",'country':"Guam"},
{'code':"GT",'country':"Gvatemala"},
{'code':"GG",'country':"Gernsi"},
{'code':"GN",'country':"Gvineya"},
{'code':"GW",'country':"Gvineya-Bisau"},
{'code':"GY",'country':"Gayana"},
{'code':"HT",'country':"Gaiti"},
{'code':"HN",'country':"Gonduras"},
{'code':"HK",'country':"Gonkong"},
{'code':"HU",'country':"Vengriya"},
{'code':"IS",'country':"Islandiya"},
{'code':"IN",'country':"Hindiston"},
{'code':"ID",'country':"Indoneziya"},
{'code':"IR",'country':"Eron"},
{'code':"IQ",'country':"Iroq"},
{'code':"IE",'country':"Irlandiya"},
{'code':"IM",'country':"Man oroli"},
{'code':"IL",'country':"Isroil"},
{'code':"IT",'country':"Italiya"},
{'code':"CI",'country':"Kot-d'Ivuar"},
{'code':"JM",'country':"Yamayka"},
{'code':"JP",'country':"Yaponiya"},
{'code':"JE",'country':"Jersi"},
{'code':"JO",'country':"Iordaniya"},
{'code':"KZ",'country':"Qozog'iston"},
{'code':"KE",'country':"Keniya"},
{'code':"KI",'country':"Kiribati"},
{'code':"XK",'country':"Kosovo"},
{'code':"KW",'country':"Quvayt"},
{'code':"KG",'country':"Qirg'iziston"},
{'code':"LA",'country':"Laos"},
{'code':"LV",'country':"Latviya"},
{'code':"LB",'country':"Livan"},
{'code':"LS",'country':"Lesoto"},
{'code':"LR",'country':"Liberiya"},
{'code':"LY",'country':"Liviya"},
{'code':"LI",'country':"Lixtenshteyn"},
{'code':"LT",'country':"Litva"},
{'code':"LU",'country':"Lyuksemburg"},
{'code':"MO",'country':"Aomin"},
{'code':"MK",'country':"Makedoniya"},
{'code':"MG",'country':"Madagaskar"},
{'code':"MW",'country':"Malavi"},
{'code':"MY",'country':"Malayziya"},
{'code':"MV",'country':"Maldiv orollari"},
{'code':"ML",'country':"Mali"},
{'code':"MT",'country':"Malta"},
{'code':"MH",'country':"Marshall orollari"},
{'code':"MR",'country':"Mavritaniya"},
{'code':"MU",'country':"Mavrikiy"},
{'code':"YT",'country':"Mayotte"},
{'code':"MX",'country':"Meksika"},
{'code':"FM",'country':"Mikroneziya"},
{'code':"MD",'country':"Moldova"},
{'code':"MC",'country':"Monako"},
{'code':"MN",'country':"Mo'g'uliston"},
{'code':"ME",'country':"Chernogoriya"},
{'code':"MS",'country':"Montserrat"},
{'code':"MA",'country':"Marokash"},
{'code':"MZ",'country':"Mozambik"},
{'code':"MM",'country':"Myanma"},
{'code':"NA",'country':"Namibiya"},
{'code':"NR",'country':"Nauru"},
{'code':"NP",'country':"Nepal"},
{'code':"NL",'country':"Nederlandiya"},
{'code':"AN",'country':"Niderlandiya G'arbiy Hindiston"},
{'code':"NC",'country':"Yangi Kaledoniya"},
{'code':"NZ",'country':"Yangi Zelandiya"},
{'code':"NI",'country':"Nikaragua"},
{'code':"NE",'country':"Niger"},
{'code':"NG",'country':"Nigeriya"},
{'code':"NU",'country':"Niue"},
{'code':"KP",'country':"Shimoliy Koreya"},
{'code':"MP",'country':"Shimoliy Mariana orollari"},
{'code':"NO",'country':"Norvegiya"},
{'code':"OM",'country':"Ummon"},
{'code':"PK",'country':"Pokiston"},
{'code':"PW",'country':"Palau"},
{'code':"PS",'country':"Falastin"},
{'code':"PA",'country':"Panama"},
{'code':"PG",'country':"Papua-Yangi Gvineya"},
{'code':"PY",'country':"Paragvay"},
{'code':"PE",'country':"Peru"},
{'code':"PH",'country':"Filippin"},
{'code':"PN",'country':"Pitkern"},
{'code':"PL",'country':"Polsha"},
{'code':"PT",'country':"Portugaliya"},
{'code':"PR",'country':"Puerto-Riko"},
{'code':"QA",'country':"Qatar"},
{'code':"CG",'country':"Kongo Respublikasi"},
{'code':"RE",'country':"Uchrashuv"},
{'code':"RO",'country':"Ruminiya"},
{'code':"RU",'country':"Rossiya"},
{'code':"RW",'country':"Ruanda"},
{'code':"BL",'country':"Sent-Bartelemi"},
{'code':"SH",'country':"Muqaddas Yelena"},
{'code':"KN",'country':"Sent-Kitts va Nevis"},
{'code':"LC",'country':"Sent-Lyusiya"},
{'code':"MF",'country':"Aziz Martin"},
{'code':"PM",'country':"Sankt-Peter va Mikelon"},
{'code':"VC",'country':"Sent-Vinsent va Grenadin orollari"},
{'code':"WS",'country':"Samoa"},
{'code':"SM",'country':"San-Marino"},
{'code':"ST",'country':"San-Tome va Prinsipi"},
{'code':"SA",'country':"Saudiya Arabistoni"},
{'code':"SN",'country':"Senegal"},
{'code':"RS",'country':"Serbiya"},
{'code':"SC",'country':"Seyshel orollari"},
{'code':"SL",'country':"Syerra-Leone"},
{'code':"SG",'country':"Singapur"},
{'code':"SX",'country':"Sint-Marten"},
{'code':"SK",'country':"Slovakiya"},
{'code':"SI",'country':"Sloveniya"},
{'code':"SB",'country':"Solomon orollari"},
{'code':"SO",'country':"Somali"},
{'code':"ZA",'country':"Janubiy Afrika"},
{'code':"KR",'country':"Janubiy Koreya"},
{'code':"SS",'country':"Janubiy Sudan"},
{'code':"ES",'country':"Ispaniya"},
{'code':"LK",'country':"Shri-Lanka"},
{'code':"SD",'country':"Sudan"},
{'code':"SR",'country':"Surinam"},
{'code':"SJ",'country':"Svalbard va Yan Mayen"},
{'code':"SZ",'country':"Svazilend"},
{'code':"SE",'country':"Shvetsiya"},
{'code':"CH",'country':"Shveytsariya"},
{'code':"SY",'country':"Suriya"},
{'code':"TW",'country':"Tayvan"},
{'code':"TJ",'country':"Tojikiston"},
{'code':"TZ",'country':"Tanzaniya"},
{'code':"TH",'country':"Tailand"},
{'code':"TG",'country':"Bormoq"},
{'code':"TK",'country':"Tokelau"},
{'code':"TO",'country':"Tonga"},
{'code':"TT",'country':"Trinidad va Tobago"},
{'code':"TN",'country':"Tunis"},
{'code':"TR",'country':"kurka"},
{'code':"TM",'country':"Turkmaniston"},
{'code':"TC",'country':"Turks va Kaykos orollari"},
{'code':"TV",'country':"Tuvalu"},
{'code':"VI",'country':"AQSh Virjiniya orollari"},
{'code':"UG",'country':"Uganda"},
{'code':"UA",'country':"Ukraina"},
{'code':"AE",'country':"Birlashgan Arab Amirliklari"},
{'code':"GB",'country':"Birlashgan Qirollik"},
{'code':"US",'country':"Qo'shma Shtatlar"},
{'code':"UY",'country':"Urugvay"},
{'code':"UZ",'country':"O'zbekiston"},
{'code':"VU",'country':"Vanuatu"},
{'code':"VA",'country':"Vatikan"},
{'code':"VE",'country':"Venesuela"},
{'code':"VN",'country':"Vetnam"},
{'code':"WF",'country':"Uollis va Futuna"},
{'code':"EH",'country':"G'arbiy Sahara"},
{'code':"YE",'country':"Yaman"},
{'code':"ZM",'country':"Zambiya"},
{'code':"ZW",'country':"Zimbabve"}]